Using App-Message Contents
tslever/Ice-Cream_Repository pull request #11
Opened 2021-01-20 21:08 UTC by tslever

to get JSON objects and pass them to appropriate process methods of Controllers. The process methods will get search criteria from the JSON objects if possible and return Products.

Modified signature of abstract method Controller.process to take JSONObject valuesPassedToController ( e.g., {"ingredients": ["cream", "sugar"]} ).

Modified ExtendedController.process to take the same input and, in the main body, not only get search criteria and get products matching search criteria, but also return empty Products if the object that is supposed to have an ingredients list doesn't or has an empty ingredients list.

Added to IceCreamApplicationMessage a method to get a String representing the body of a client message.

Implemented SearchCriteria.

Added to MessageHandler a method to add controllers. Rewrote handle to split the body of a client message into (key_plus_values)'s. Each key_plus_values is split into a key and values, which forms a row in a hashMap, if it is valid and hasn't already been added to the hashMap. For each row, the values are decoded and used to construct a JSON object, which is passed to the process method of a Controller identified by the key in the row.

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall requested changes
This looks pretty good, but I have a few comments that should be addressed. Also, I know you want me to put my comment about the Java warning about exporting a private type, but I can't figure out where to do that.  Will you annotate, with a comment, the line where that warning is being given?

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/Controller.java
> +    abstract public void process(JSONObject valuesPassedToController);
I think at the Controller level (since it is abstract) it would be better not to restrict it to a JSONObject, but maybe make it even more general (whatever the Java class or construct is that means Any Object). We don't want to restrict all implementations of Controller to always use JSON; sometimes it could be XML, sometimes something application-specific. That is one of the purposes of making it abstract.

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +        public void process(JSONObject valuesToUse) {
Why, since this is an IceCream-specific class, did you generalize this paramtere to JSONObject.  Would it be better instead to have IceCreamApplicationMessage have a method to return whatever is relevant as a JSONObject, or to have IceCreamApplicationMessage extend JSONObject?

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +            if (valuesToUse.has("invalid-key") &&
I think this is good...rather than putting these checks into Retriever.getTheProductsMatching.

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
>          private SearchCriteria getSearchCriteria(
This should not be internal to the method 'process'. It should be a private method within IceCreamClientCommunication.

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +                objectWithIngredientList.getJSONArray("ingredients");
This is a duplication of code done at a higher level (two levels up, I think).  Since the higher level is checking for the existence of "ingredients" and returning an empty array if it is not found, if it **IS** found at that level then that level should only pass the object designated by "ingredients" to the method that it invokes.

2021-01-21 18:46 UTC, Chip-at-Twirling-Hall commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/MessageHandler.java
>      @Override
This method is way too long, and too many nested levels.

2021-01-23 01:27 UTC, tslever commented
> This looks pretty good, but I have a few comments that should be addressed. Also, I know you want me to put my comment about the Java warning about exporting a private type, but I can't figure out where to do that. Will you annotate, with a comment, the line where that warning is being given? @tslever

The warning "Exporting non-public type through public API" is associated with the signature "public void setMessageInterfaces(MessageInterface[] messageInterfacesToUse) throws Exception { ... }" in Server.java.

2021-01-24 23:28 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/Controller.java
> +    abstract public void process(JSONObject valuesPassedToController);
I declared abstract method Controller.process to take as input Object valuesToUse. In ExtendedController.process, I defined valuesToUseAsJSONObject as valuesToUse cast to a JSONObject. I did this knowing that MessageHandler.handle calls passes to process a JSONObject. In the case that handle were to pass a non-JSONObject, how would I test if the passed thing was a JSONObject or not?

2021-01-25 00:06 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
>          private SearchCriteria getSearchCriteria(
I changed getSearchCriteria from being a private method within ExtendedController to being a private method within IceCreamClientCommunication.

2021-01-25 00:25 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +                objectWithIngredientList.getJSONArray("ingredients");
I moved definition of ingredientsListAsJSONArray to ExtendedController.process after "if (!valuesToUseAsJSONObject.has("ingredients")) { ... }".

2021-01-25 00:27 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +            if (valuesToUse.has("invalid-key") &&
Thanks.

2021-01-25 00:56 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/MessageHandler.java
>      @Override
Let's start with a summary of what handle does as of 01/24/21 19:55.

1. MessageHandler.handle gets an ice cream application message from httpExchange.
2. handle gets the body of the ice cream application message.
3. handle defines an array of strings, each with a key to identify a controller and values to pass to the controller.
4. handle, for each string with a key to identify a controller and values to pass to the controller: a) converts the present string to a two-element array of string key and string values; b) adds key and values to a hash map if the hash map doesn't already contain key, key corresponds to a controller, and key isn't "invalid-key"; and c) adds key "invalid-key" and values "{'invalid-key': 'no-valid-keys'}" to the hash map if no keys and values were added to the hash map.
5. handle, for each key in the hash map, a) tries to decode the values associated with that key from URL encoding to JSON format; b) constructs a JSONObject based on the decoded values; and c) calls the process method of the controller associated with that key, passing the process method the JSONObject representing values.

2021-01-25 01:50 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/MessageHandler.java
>      @Override
I rewrote method handle to:

1. Extract the ice cream application message in an HTTP message,
2. Get the body of the ice cream application message,
3. Define an array of strings, each with a key to identify a controller and values to pass to the controller,
4. Define a hash map of keys and values (by calling defineHashMapOfKeysAndValues), and
5. Have controllers process values (by calling haveControllersProcessValues).


See commit "Addressed comments in PR-11 by" below for details.

2021-01-25 03:16 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/IceCreamClientCommunication.java
> +        public void process(JSONObject valuesToUse) {
I'm passing into a ExtendedController.process method a piece of an IceCreamApplicationMessage, not an IceCreamApplicationMessage.

2021-01-25 03:23 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/Controller.java
> +    abstract public void process(JSONObject valuesPassedToController);
We had process throw an exception if input parameter valuesToUse is not a JSONObject.

2021-01-25 03:26 UTC, tslever commented on Server_Stuff/icecreamserver/src/main/java/com/mycompany/serverutilities/clientcommunicationutilities/MessageHandler.java
>      @Override
We improved cohesion in handle to have handle just get ice cream application message and pass its body to defineHashMapOfKeysAndValues.

2021-01-25 04:16 UTC, merged